version: '1.29.2'

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/mariadb

services:
  maria_db:
    container_name: maria_db
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 3306

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - maria_db
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_PORT: ${WORDPRESS_DB_PORT}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      DB_HOST: ${WORDPRESS_DB_HOST}
      DB_NAME: ${WORDPRESS_DB_NAME}
      DB_USER: ${WORDPRESS_DB_USER}
      DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    expose:
      - 9000

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "80:80"
    restart: unless-stopped
