version:  '3.8'

services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - MDB_DATABASE
        - MDB_USER
        - MDB_PASS
    image: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - mariadb_volume:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      args:
        - MDB_DATABASE
        - MDB_USER
        - MDB_PASS
    image: wordpress
    restart: always
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - mariadb
  
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    image: nginx
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
  
networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_volume:
    driver_opts:
      o: bind
      type: none
      device: ${PATH_VOLUME}/mariadb
  wordpress_volume:
    driver_opts:
      o: bind
      type: none
      device: ${PATH_VOLUME}/wordpress